networks:
  d-storage-network:
    driver: bridge

volumes:
  ipfs-data:
    driver: local
    name: ipfs-data

services:
  ipfs:
    privileged: true
    image: ipfs/kubo:latest
    user: "0:0"
    ports:
      - 5001:5001
      - 4001:4001
      - 8080:8080
    networks: 
      - d-storage-network
    volumes:
      - ./data/ipfs:/data/ipfs
    restart: unless-stopped
  
  backend:
    privileged: true
    build: ./backend
    container_name: d-storage-backend
    ports:
      - 3002:3002
    networks:
      - d-storage-network
    env_file:
      - .env
    depends_on:
      - ipfs
  
  frontend:
    build: ./frontend
    container_name: d-storage-frontend
    networks:
      - d-storage-network
    env_file:
      - .env
    ports:
      - 3000:3000
  
